# MoodleClaude v3.0 - Guaranteed Fresh Installation
# Forces new installation every time

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: moodleclaude_postgres_fresh
    restart: unless-stopped
    environment:
      POSTGRES_DB: moodle_fresh
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: MoodleFresh2025!
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    networks:
      - moodle_fresh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moodle -d moodle_fresh"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    # No volumes - fresh database every time

  # Fresh Moodle Installation
  moodle:
    image: bitnami/moodle:4.3
    container_name: moodleclaude_app_fresh
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database Configuration
      MOODLE_DATABASE_TYPE: pgsql
      MOODLE_DATABASE_HOST: postgres
      MOODLE_DATABASE_PORT_NUMBER: 5432
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: MoodleFresh2025!
      MOODLE_DATABASE_NAME: moodle_fresh
      
      # Fresh Admin Configuration
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: Fresh2025Admin!
      MOODLE_EMAIL: admin@moodleclaude.com
      MOODLE_SITE_NAME: "MoodleClaude v3.0 Fresh Installation"
      
      # Force fresh installation
      MOODLE_SKIP_BOOTSTRAP: "no"
      MOODLE_SKIP_INSTALL: "no"
      
      # Optimized Settings
      PHP_MEMORY_LIMIT: 512M
      PHP_POST_MAX_SIZE: 100M
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_MAX_EXECUTION_TIME: 300
      PHP_MAX_INPUT_VARS: 5000
      
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - moodle_fresh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login/index.php"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 180s
    # No persistent volumes - completely fresh every time

  # Database Admin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: moodleclaude_pgadmin_fresh
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: Fresh2025Admin!
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8082:80"
    networks:
      - moodle_fresh
    depends_on:
      - postgres

networks:
  moodle_fresh:
    driver: bridge
    name: moodle_fresh_network

# No volumes section = no persistent data = always fresh!